// Generated by CoffeeScript 1.12.4
(function() {
  var Session, bcrypt, log;

  log = require('../../log');

  bcrypt = require('bcrypt');

  Session = require('../../logic/session');

  module.exports = {
    checkPasswordValidity: function(arg, cb) {
      var args, login;
      args = arg.args, login = arg.login;
      log('Running task: checkPasswordValidity', {
        args: args,
        login: login
      });
      if (bcrypt.compareSync(args.password, login.get('password'))) {
        return cb({});
      } else {
        return cb({
          error: 'login failed',
          description: 'Password mismatch',
          message: 'The password you entered did not match'
        });
      }
    },
    addUserToSession: function(arg, cb) {
      var login, session;
      session = arg.session, login = arg.login;
      log('Running task: addUserToSession');
      return Session.set(session, 'userId', login.get('userId'), function() {
        return cb({});
      });
    }
  };

}).call(this);
