// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c, h;

  Plan = require('../helpers/plan');

  c = require('../common_tasks');

  h = require('./helper');

  module.exports = Plan(c.getSession, c.ensureHasArgs('name', 'password'), c.findOne('login.name = args.name'), h.checkPasswordValidity, h.addUserToSession, function(arg, cb) {
    var login, session;
    session = arg.session, login = arg.login;
    return cb({
      session: {
        id: session,
        userId: login.get('userId')
      }
    });
  });

}).call(this);
