// Generated by CoffeeScript 1.12.4
(function() {
  var child_process, query;

  process.env.DATABASE_URL = 'postgres://mika:mika@localhost/test';

  query = require('../');

  child_process = require('child_process');

  module.exports = function(cb) {
    return query("select 'drop table if exists \"' || tablename || '\" cascade;' AS q from pg_tables WHERE schemaname = 'public';", function(rows) {
      var qu, queries;
      console.log('=== Totally wiped database');
      queries = ((function() {
        var i, len, results;
        results = [];
        for (i = 0, len = rows.length; i < len; i++) {
          qu = rows[i];
          results.push(qu.q);
        }
        return results;
      })()).join('');
      return query(queries, function() {
        var dir, file, i, len, normalizedPath;
        normalizedPath = require("path").join(__dirname, "../migrations");
        dir = require("fs").readdirSync(normalizedPath);
        for (i = 0, len = dir.length; i < len; i++) {
          file = dir[i];
          if (!(file === 'index.coffee' || file[0] === '.')) {
            file = 'server/db/migrations/' + file;
            console.log('=== Migrating ' + file);
            child_process.execSync("coffee " + file);
          }
        }
        return cb();
      });
    });
  };

}).call(this);
