// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  c = require('../common_tasks');

  Plan = require('./plan');

  module.exports = Plan.async(c.findAll('booking.buyerUserId == user.id'), c.findAll('booking.sellerUserId == user.id'));

}).call(this);
