// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  module.exports = Plan = require('../../../common/plan');

  c = require('../common_tasks');

  Plan["private"] = {
    update: function(what) {
      return Plan(c.set('args.userId = undefined'), c.validateArgs(what, {
        partial: true
      }), c.getLoggedInUser, c.findOne(what + ".id == args.id"), c.ensure(what + ".userId == user.id"), c.update(what));
    },
    create: function(what, arg) {
      var mustHave;
      mustHave = (arg != null ? arg : {}).mustHave;
      return Plan(c.getLoggedInUser, c.validateArgs(what), c.ensure('args.userId == user.id'), c.create(what));
    },
    createMaxOne: function(what) {
      return Plan(c.getLoggedInUser, c.validateArgs(what), c.ensure('args.userId = user.id'), c.findNo(what + ".userId == user.id"), c.create(what));
    }
  };

  Plan["public"] = {
    retrieve: function(what) {
      return Plan(c.retrieveAll(what));
    }
  };

}).call(this);
