// Generated by CoffeeScript 1.12.4
(function() {
  var Balance, Model;

  Model = require('./model');

  module.exports = Balance = Model({
    tableName: 'balances',
    columns: {
      userId: ['user_id', 'text'],
      hours: ['hours', 'text']
    }
  });

}).call(this);
