// Generated by CoffeeScript 1.12.4
(function() {
  var Bonus, Model;

  Model = require('./model');

  module.exports = Bonus = Model({
    tableName: 'bonuses',
    columns: {
      userId: ['user_id', 'text'],
      hours: ['hours', 'text']
    }
  });

}).call(this);
