// Generated by CoffeeScript 1.12.4
(function() {
  var BookingReviewPrivate, Model;

  Model = require('./model');

  module.exports = BookingReviewPrivate = Model({
    tableName: 'booking_review_private',
    columns: {
      bookingId: ['booking_id', 'text'],
      message: ['message', 'text']
    }
  });

}).call(this);
