// Generated by CoffeeScript 1.12.4
(function() {
  var BookingMessage, Model;

  Model = require('./model');

  module.exports = BookingMessage = Model({
    tableName: 'booking_messages',
    columns: {
      bookingId: ['booking_id', 'text'],
      userId: ['user_id', 'text'],
      message: ['message', 'text']
    }
  });

}).call(this);
