// Generated by CoffeeScript 1.12.4
(function() {
  var BookingDeal, Model;

  Model = require('./model');

  module.exports = BookingDeal = Model({
    tableName: 'booking_deal',
    columns: {
      bookingId: ['booking_id', 'text'],
      hours: ['hours', 'text'],
      time: ['time', 'text']
    }
  });

}).call(this);
