// Generated by CoffeeScript 1.12.4
(function() {
  var Booking, Model;

  Model = require('./model');

  module.exports = Booking = Model({
    tableName: 'bookings',
    columns: {
      adId: ['ad_id', 'text'],
      buyerUserId: ['buyer_user_id', 'text'],
      sellerUserId: ['seller_user_id', 'text']
    }
  });

}).call(this);
