// Generated by CoffeeScript 1.12.4
(function() {
  var BookingRequest, Model;

  Model = require('./model');

  module.exports = BookingRequest = Model({
    tableName: 'booking_refusal',
    columns: {
      bookingId: ['booking_id', 'text'],
      userId: ['user_id', 'text']
    }
  });

}).call(this);
