// Generated by CoffeeScript 1.12.4
(function() {
  var BookingRequest, Model;

  Model = require('./model');

  module.exports = BookingRequest = Model({
    tableName: 'booking_proposal',
    columns: {
      bookingId: ['booking_id', 'text'],
      hours: ['hours', 'text'],
      time: ['time', 'text']
    }
  });

}).call(this);
