// Generated by CoffeeScript 1.12.4
(function() {
  var BookingReviewDooify, Model;

  Model = require('./model');

  module.exports = BookingReviewDooify = Model({
    tableName: 'booking_review_dooify',
    columns: {
      bookingId: ['booking_id', 'text'],
      message: ['messsage', 'text']
    }
  });

}).call(this);
