// Generated by CoffeeScript 1.12.4
(function() {
  var BookingReviewPublic, Model;

  Model = require('./model');

  module.exports = BookingReviewPublic = Model({
    tableName: 'booking_review_public',
    columns: {
      bookingId: ['booking_id', 'text'],
      rating: ['rating', 'text'],
      message: ['message', 'text']
    }
  });

}).call(this);
