// Generated by CoffeeScript 1.12.4
(function() {
  var Changes, Model;

  Model = require('./model');

  module.exports = Changes = Model({
    tableName: 'changes',
    columns: {
      klassName: ['klass', 'text'],
      klassId: ['klass_id', 'text'],
      klassCreatedAt: ['klass_created_at', 'text']
    }
  });

}).call(this);
