// Generated by CoffeeScript 1.12.4
(function() {
  var Model, Profile;

  Model = require('./model');

  module.exports = Profile = Model({
    tableName: 'contacts',
    columns: {
      userId: ['user_id', 'text'],
      mail: ['mail', 'text']
    }
  });

}).call(this);
