// Generated by CoffeeScript 1.12.4
(function() {
  var Login, Model;

  Model = require('./model');

  module.exports = Login = Model({
    tableName: 'facebook_login',
    columns: {
      userId: ['user_id', 'text'],
      fbUserId: ['fb_user_id', 'text']
    }
  });

}).call(this);
