// Generated by CoffeeScript 1.12.4
(function() {
  var Heartbeat, Model;

  Model = require('./model');

  module.exports = Heartbeat = Model({
    tableName: 'heartbeat',
    columns: {
      identifier: ['identifier', 'text'],
      userId: ['user_id', 'text'],
      isLoggedIn: ['is_logged_in', 'boolean'],
      page: ['page', 'text'],
      resource: ['resource', 'text']
    }
  });

}).call(this);
