// Generated by CoffeeScript 1.12.4
(function() {
  var Image, Model;

  Model = require('./model');

  module.exports = Image = Model({
    tableName: 'images',
    columns: {
      userId: ['user_id', 'text'],
      image: ['original', 'text']
    }
  });

}).call(this);
