// Generated by CoffeeScript 1.12.4
(function() {
  var Image360, Model;

  Model = require('./model');

  module.exports = Image360 = Model({
    tableName: 'images_750',
    columns: {
      imageId: ['image_id', 'text'],
      image: ['image', 'text']
    }
  });

}).call(this);
