// Generated by CoffeeScript 1.12.4
(function() {
  var Login, Model;

  Model = require('./model');

  module.exports = Login = Model({
    tableName: 'logins',
    columns: {
      userId: ['user_id', 'text'],
      name: ['name', 'text'],
      password: ['password', 'text']
    }
  });

}).call(this);
