// Generated by CoffeeScript 1.12.4
(function() {
  var MailValidation, Model;

  Model = require('./model');

  module.exports = MailValidation = Model({
    tableName: 'mail_validations',
    columns: {
      userId: ['user_id', 'text'],
      activation_code: ['activation_code', 'text'],
      isValidated: ['is_validated', 'boolean']
    }
  });

}).call(this);
