// Generated by CoffeeScript 1.12.4
(function() {
  var Model, Profile;

  Model = require('./model');

  module.exports = Profile = Model({
    tableName: 'profiles',
    columns: {
      userId: ['user_id', 'text'],
      firstName: ['first_name', 'text'],
      lastName: ['last_name', 'text'],
      description: ['description', 'text'],
      imageId: ['image_id', 'text'],
      language: ['language', 'text']
    }
  });

}).call(this);
