// Generated by CoffeeScript 1.12.4
(function() {
  var Model, Session;

  Model = require('./model');

  module.exports = Session = Model({
    tableName: 'sessions',
    columns: {
      userId: ['user_id', 'text']
    }
  });

}).call(this);
