// Generated by CoffeeScript 1.12.4
(function() {
  var Model, Subscription;

  Model = require('./model');

  module.exports = Subscription = Model({
    tableName: 'subscriptions',
    columns: {
      userId: ['user_id', 'text']
    }
  });

}).call(this);
