// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  module.exports = Plan(c.getLoggedInUser, c.validateArgs('image'), c.ensure('args.userId == user.id'), c.create('image'), function(arg, cb) {
    var image;
    image = arg.image;
    image = image.dump();
    delete image.image;
    return cb({
      image: image
    });
  });

}).call(this);
