// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c, dump, setArgs;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  setArgs = function(arg, cb) {
    var args, session, userId;
    session = arg.session, userId = arg.userId, args = arg.args;
    args.identifier = session;
    args.userId = userId;
    args.isLoggedIn = (userId ? true : false);
    return cb({});
  };

  dump = function(args, cb) {
    return cb({
      success: true
    });
  };

  module.exports = Plan(c.getSession, setArgs, c.create('heartbeat'), dump);

}).call(this);
