// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c, createBooking, createBookingRequest, mail, sendMail;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  mail = require('../mail/request');

  createBooking = Plan(c.set("a = {}\na.adId = args.adId\na.buyerUserId = user.id\na.sellerUserId = ad.userId\nargs = a"), c.ensure('args.buyerUserId != args.sellerUserId'), c.create('booking'));

  createBookingRequest = Plan(c.set("a = {}\na.bookingId = booking.id\na.message = args.message\nargs = a"), c.validateArgs('booking_request'), c.create('booking_request'));

  sendMail = Plan(c.findOne('profile.userId = booking.sellerUserId', {
    rename: 'seller'
  }), c.findOne('profile.userId = booking.buyerUserId', {
    rename: 'buyer'
  }), c.findOne('contact.userId = booking.sellerUserId'), function(arg, cb) {
    var ad, booking, buyer, code, contact, seller;
    booking = arg.booking, buyer = arg.buyer, seller = arg.seller, contact = arg.contact, code = arg.code, ad = arg.ad;
    return mail({
      buyer: buyer,
      seller: seller,
      booking: booking,
      ad: ad,
      to: contact.get('mail')
    }, cb);
  });

  module.exports = Plan(c.getLoggedInUser, c.findOne('ad.id = args.adId'), createBooking, createBookingRequest, sendMail, c.select('booking_request', 'booking'));

}).call(this);
