// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, User, c, findVito;

  c = require('./common_tasks');

  Plan = require('./helpers/plan');

  User = require('../db/user');

  findVito = function(arg, cb) {
    var args, startOfUserId;
    args = arg.args;
    startOfUserId = args.vitoUserId;
    return User.where({}, function(users) {
      var i, len, u;
      for (i = 0, len = users.length; i < len; i++) {
        u = users[i];
        if (u.get('id').slice(0, 6) === startOfUserId) {
          args.vitoUserId = u.get('id');
          cb({});
          return;
        }
      }
      return cb({
        error: {
          id: 'does not exist',
          description: 'Could not find a user with that referral code'
        }
      });
    });
  };

  module.exports = function(stuff, cb) {
    return Plan(c.getLoggedInUser, findVito, c.validateArgs('referral'), c.set('args.isActivated = false'), c.set('args.hours = 1'), c.ensure('args.lucaUserId == user.id'), c.ensure('args.lucaUserId != args.vitoUserId', 'You cannot recruit yourself!'), c.findNo('referral.lucaUserId == user.id'), c.create('referral'))(stuff, function(answer) {
      if (answer.error) {
        return cb({});
      } else {
        return cb(answer);
      }
    });
  };

}).call(this);
