// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c, dump, mailValidation, sendMail;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  sendMail = require('../mail/send');

  mailValidation = function(arg, cb) {
    var args, done, i, len, rec, results, sent, to;
    args = arg.args;
    to = ['mika@dooify.com', 'louise@dooify.com', 'carl@dooify.com'];
    sent = 0;
    done = function() {
      sent += 1;
      if (sent === to.length) {
        return cb({});
      }
    };
    results = [];
    for (i = 0, len = to.length; i < len; i++) {
      rec = to[i];
      results.push(sendMail({
        subject: "Feedback from " + args.name,
        to: rec,
        from: args.mail,
        text: args.message
      }, done));
    }
    return results;
  };

  dump = function(args, cb) {
    return cb({
      success: true
    });
  };

  module.exports = Plan(c.getSession, mailValidation, dump);

}).call(this);
