// Generated by CoffeeScript 1.12.4
(function() {
  var Bonus, MailValidation, Plan, Session, User, _activateReferral, activateOnlyIfNotActivated, activateReferral, c, grantBonus, markAsValidated, redirect, setSessObj, setSessionUser;

  Plan = require('./helpers/plan');

  Session = require('../logic/session');

  c = require('./common_tasks');

  MailValidation = require('../db/mail_validation');

  User = require('../db/user');

  Bonus = require('../db/bonus');

  activateReferral = require('./activate_referral');

  setSessObj = function(arg, cb) {
    var ret, session, userId;
    userId = arg.userId, session = arg.session;
    ret = {
      id: session
    };
    if (userId) {
      ret.userId = userId;
    }
    return cb({
      session: ret
    });
  };

  activateOnlyIfNotActivated = function(args, cb) {
    if (args.mail_validation.get('isValidated') !== true) {
      return Plan(c.findOne('user.id == mail_validation.userId'), setSessionUser, grantBonus, markAsValidated, _activateReferral)(args, cb);
    } else {
      return cb({});
    }
  };

  grantBonus = function(arg, cb) {
    var bonus, user;
    user = arg.user;
    bonus = Bonus({
      userId: user.get('id'),
      hours: '2'
    });
    return bonus.save(function() {
      return cb({
        bonus: bonus
      });
    });
  };

  markAsValidated = function(arg, cb) {
    var mail_validation;
    mail_validation = arg.mail_validation;
    mail_validation.set('isValidated', true);
    return mail_validation.save(function() {
      return cb({});
    });
  };

  _activateReferral = function(arg, cb) {
    var user;
    user = arg.user;
    return activateReferral({
      lucaUserId: user.get('id')
    }, function(result) {
      if (result.error) {
        return cb({});
      } else {
        return cb({
          referral: result.referral
        });
      }
    });
  };

  setSessionUser = function(arg, cb) {
    var session, user;
    session = arg.session, user = arg.user;
    return Session.set(session.id, 'userId', user.get('id'), function() {
      session.userId = user.get('id');
      return cb({});
    });
  };

  redirect = function(args, cb) {
    return cb({});
  };

  module.exports = Plan(c.getSession, setSessObj, c.findOne('mail_validation.activation_code == args.code'), activateOnlyIfNotActivated, c.select('session', 'mail_validation', 'referral', 'bonus'));

}).call(this);
