// Generated by CoffeeScript 1.12.4
(function() {
  var Image, Plan, c, fetchSpecial;

  c = require('./common_tasks');

  Plan = require('./helpers/plan');

  Image = require('../db/image');

  fetchSpecial = function(arg, cb) {
    var user;
    user = arg.user;
    return Image.where({
      userId: user.get('id')
    }, {
      exclude: 'image'
    }, function(results) {
      var i, len, r, results1;
      results1 = [];
      for (i = 0, len = results.length; i < len; i++) {
        r = results[i];
        delete r.image;
        results1.push(cb({
          image: r
        }));
      }
      return results1;
    });
  };

  module.exports = Plan(c.getLoggedInUser, fetchSpecial);

}).call(this);
