// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  module.exports = Plan(c.getLoggedInUser, c.ensure('args.id == user.id'), c.select('user'));

}).call(this);
