// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, Referral, c, fetchSpecial;

  c = require('./common_tasks');

  Plan = require('./helpers/plan');

  Referral = require('../db/referral');

  fetchSpecial = function(arg, cb) {
    var user;
    user = arg.user;
    return Referral.where({
      or: {
        vitoUserId: user.get('id'),
        lucaUserId: user.get('id')
      }
    }, function(results) {
      var i, len, r, results1;
      results1 = [];
      for (i = 0, len = results.length; i < len; i++) {
        r = results[i];
        results1.push(cb({
          referral: r
        }));
      }
      return results1;
    });
  };

  module.exports = Plan(c.getLoggedInUser, Plan.async(c.findAll('referral.vitoUserId == user.id'), c.findAll('referral.lucaUserId == user.id')));

}).call(this);
