// Generated by CoffeeScript 1.12.4
(function() {
  var Session, getSession;

  Session = require('../logic/session');

  module.exports = getSession = function(arg, cb) {
    var session;
    session = arg.session;
    return Session.validate(session, function(isValid) {
      if (isValid) {
        return Session.get(session, 'userId', function(userId) {
          if (userId) {
            return cb({
              userId: userId
            });
          } else {
            return cb({});
          }
        });
      } else {
        return Session.create(function(id) {
          return cb({
            session: {
              id: id
            }
          });
        });
      }
    });
  };

}).call(this);
