// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  c = require('./common_tasks');

  Plan = require('./helpers/plan');

  module.exports = Plan(function(args, cb) {
    var ads, picked;
    ads = [];
    picked = {};
    return Plan(c.findAll('ad'), function(arg, cb) {
      var ad;
      ad = arg.ad;
      return ads.push(ad);
    })({}).then(function() {
      var ad, r, results, target;
      target = 8;
      if (ads.length < target) {
        target = Math.ceil(ads.length / 2);
      }
      results = [];
      while (target > 0) {
        target -= 1;
        ad = ads[Math.floor(Math.random() * ads.length)];
        while (picked[ad.get('id')]) {
          ad = ads[Math.floor(Math.random() * ads.length)];
        }
        picked[ad.get('id')] = true;
        r = {
          recommendation: {
            id: ad.get('id'),
            adId: ad.get('id')
          }
        };
        results.push(cb(r));
      }
      return results;
    });
  });

}).call(this);
