// Generated by CoffeeScript 1.12.4
(function() {
  var Plan, c;

  Plan = require('./helpers/plan');

  c = require('./common_tasks');

  module.exports = Plan(c.getLoggedInUser, c.findOne('ad.id = args.id'), c.ensure('ad.userId == user.id'), c.remove('ad'));

}).call(this);
