// Generated by CoffeeScript 1.12.4
(function() {
  var Session;

  Session = require('../logic/session');

  module.exports = function(arg, cb) {
    var session;
    session = arg.session;
    return Session.set(session, 'userId', void 0, function() {
      return cb({
        session: {
          isDeleted: true
        }
      });
    });
  };

}).call(this);
