// Generated by CoffeeScript 1.12.4
(function() {
  var Session, User;

  Session = require('../logic/session');

  User = require('../db/user');

  module.exports = function(arg, cb) {
    var args, session;
    session = arg.session, args = arg.args;
    return Session.validate(args.id, function(isValid) {
      if (isValid) {
        return Session.get(args.id, 'userId', function(userId) {
          var user;
          if (!userId) {
            return cb({
              session: {
                id: args.id
              }
            });
          } else {
            return user = User.find(userId, function(user) {
              if (user) {
                return cb({
                  session: {
                    id: args.id,
                    userId: userId
                  }
                });
              } else {
                return cb({
                  session: {
                    id: args.id
                  }
                });
              }
            });
          }
        });
      } else {
        return Session.create(function(id) {
          return cb({
            session: {
              id: id
            }
          });
        });
      }
    });
  };

}).call(this);
