// Generated by CoffeeScript 1.12.4
(function() {
  var Query, parse;

  parse = require('./parse');

  module.exports = Query = function(what) {
    var Model, q;
    q = parse(what);
    Model = require('../../db/' + q.targetName);
    q.run = function(args, cb) {
      var matcher;
      matcher = {};
      if (q.hasConstraint) {
        matcher[q.targetColumn] = q.getConstraintValue(args);
      }
      return Model.where(matcher, function(results) {
        return cb(results, matcher);
      });
    };
    return q;
  };

}).call(this);
